version: "3.8" # 버전 지정

services: # 컨테이너 설정
  ###################################
  #### Reverse Proxy Server
  ###################################
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80/tcp
      - 443:443 # https
    depends_on:
      - api-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - TZ=Asia/Seoul


  ###################################
  #### API Server
  ###################################
  api-server:
    container_name: api-server
    restart: always # 다운시 항상 재시작
    image: idgafff010/semtle-youtube-clone-spring-app:latest
    ports:
      - 8080:8080
    environment:
      - database-url=${DATABASE_URL}
      - database-username=${DATABASE_USERNAME}
      - database-password=${DATABASE_PASSWORD}