spring:
  mvc:
    static-path-pattern: /webapp/**
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database-url}/youtube_clone?serverTimezone=UTC
    username: ${database-username}
    password: ${database-password}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: debug
# 미디어 서버와 통신하기 위한 url : ex) http://localhost:8080
media-server:
  url: http://129.154.59.47:80
auth:
  secret-key: secretadsfsdfsdfasdfasdfasdfasdfaasdfasdfasdfasdfasdfasdfaf
  token-expiration-msec: 864000000